### ISSUE TITLE
Hi and question/issue: Doc's Availability

### ISSUE THREAD

**Issue by mangmang2006** [rishikesh1419/HelloDoc#3]
Hi there, just found your excellent work here. I haven't read through everything, but just wonder if your code has the function for doctors to publish their available time slots, so that when patients try to make an appointment, they know they are not blindly booking doctors.

Best Regards,
Clark

**Comment by rishikesh1419** [comment]
No, this function is not provided yet. The slots are fixed.
You may want to add another form for input and a table for storing available appointment slots.
Just link that table to the existing drop-down menu which appears while booking an appointment.
Collaboration is highly appreciated!
